apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: python:3.9-slim
        command: ["python3", "-m", "http.server", "8080"]
        workingDir: /app
        volumeMounts:
          - name: html
            mountPath: /app
      volumes:
        - name: html
          configMap:
            name: hello-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html
data:
  index.html: |
    <html>
    <head><title>Hello Cloud</title></head>
    <body><h1>Bienvenue sur votre premier service Kubernetes !</h1></body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
