---
- name: Provision VM with Minikube and deploy services
  hosts: minikube_vms
  become: yes

  tasks:
    - name: Update APT
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - conntrack
          - socat
          - docker.io
        state: present

    - name: Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Start Minikube
      shell: minikube start --driver=none
      environment:
        CHANGE_MINIKUBE_NONE_USER: "true"

    - name: Copy Kubernetes manifests
      copy:
        src: ../k8s/services/
        dest: /home/{{ ansible_user }}/services/
        mode: 0755

    - name: Build custom Flask Docker image
      docker_image:
        name: flask-custom
        path: ../app
        tag: latest
        state: present

    - name: Deploy hello-app
      shell: |
        kubectl apply -f /home/{{ ansible_user }}/services/hello-app
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Deploy flask-app
      shell: |
        kubectl apply -f /home/{{ ansible_user }}/services/flask-app
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
