---
- name: Provision VM with K3s and deploy services
  hosts: k3s_nodes
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
        state: present
        update_cache: yes

    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      shell: |
        until kubectl get nodes; do sleep 2; done
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Copy Kubernetes manifests
      copy:
        src: ../k8s/services/
        dest: /home/{{ ansible_user }}/services/
        mode: 0755

    - name: Deploy hello-app
      shell: |
        kubectl apply -f /home/{{ ansible_user }}/services/hello-app
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Deploy portainer
      shell: |
        kubectl apply -f /home/{{ ansible_user }}/services/portainer
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
